baseURL = 'https://hankli0130.github.io/zoomkeeper/'
languageCode = 'en-ca'
title = 'Zoomkeeper Studio'
theme = 'creative-portfolio'

[params]
  style = "blue"
  description = "Professional Headshot Studio"
  copyright = "&copy;2022 Zoomkeeper Studio"
  sidebarAbout = [
    "📷 The best Photographer/ Videographer in Toronto, Ontario, Canada",
    "📱 437 989 6426",
    "👋 Zoomkeeper Studio - AJ"
  ]

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "portfolio/"
  home = true

  [params.social]
  email         = "zoomkeeperstudio@gmail.com"
  instagram     = "https://www.instagram.com/zoomkeeperstudio/"
  youtube       = "https://www.youtube.com/channel/UCp43nxaI89Qz6j9hNEIzQDw/videos"